version: "3.9"

services:
  backend:
    build: ./backend
    container_name: easyfest-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/app/.tmp
    ports:
      - "1337:1337"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: easyfest-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
