services:
  backend:
    build: ./backend
    container_name: easyfest-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/app/.tmp
      - ./backend/public/uploads:/app/public/uploads
    expose:
      - "1337"
    ports:
      - "1337:1337"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: easyfest-frontend
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: easyfest-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    restart: unless-stopped
